// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

class SurrealdbImpl implements Surrealdb {
  final SurrealdbPlatform _platform;
  factory SurrealdbImpl(ExternalLibrary dylib) =>
      SurrealdbImpl.raw(SurrealdbPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory SurrealdbImpl.wasm(FutureOr<WasmModule> module) =>
      SurrealdbImpl(module as ExternalLibrary);
  SurrealdbImpl.raw(this._platform);
  Stream<void> connectMethodSurrealDb(
      {required SurrealDB that, required String endpoint, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_surreal_db(that);
    var arg1 = _platform.api2wire_String(endpoint);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_connect__method__SurrealDB(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      parseErrorData: null,
      constMeta: kConnectMethodSurrealDbConstMeta,
      argValues: [that, endpoint],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kConnectMethodSurrealDbConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "connect__method__SurrealDB",
        argNames: ["that", "endpoint"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
