// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class SurrealdbPlatform extends FlutterRustBridgeBase<SurrealdbWire>
    with FlutterRustBridgeSetupMixin {
  SurrealdbPlatform(FutureOr<WasmModule> dylib) : super(SurrealdbWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  Object api2wire_SurrealAny(SurrealAny raw) {
    return raw.shareOrMove();
  }

  @protected
  List<dynamic> api2wire_box_autoadd_surreal_db(SurrealDB raw) {
    return api2wire_surreal_db(raw);
  }

  @protected
  List<dynamic> api2wire_surreal_db(SurrealDB raw) {
    return [api2wire_SurrealAny(raw.db)];
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external SurrealdbWasmModule get wasmModule;

@JS()
@anonymous
class SurrealdbWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external SurrealdbWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_connect__method__SurrealDB(
      NativePortType port_, List<dynamic> that, String endpoint);
}

// Section: WASM wire connector

class SurrealdbWire extends FlutterRustBridgeWasmWireBase<SurrealdbWasmModule> {
  SurrealdbWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<SurrealdbWasmModule>(module));

  void wire_connect__method__SurrealDB(
          NativePortType port_, List<dynamic> that, String endpoint) =>
      wasmModule.wire_connect__method__SurrealDB(port_, that, endpoint);
}
