// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Surrealdb {
  Stream<void> connectMethodSurrealDb(
      {required SurrealDB that, required String endpoint, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kConnectMethodSurrealDbConstMeta;
}

@sealed
class SurrealAny extends FrbOpaque {
  final Surrealdb bridge;
  SurrealAny.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueSurrealAny;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueSurrealAny;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.SurrealAnyFinalizer;
}

class SurrealDB {
  final Surrealdb bridge;
  final SurrealAny db;

  const SurrealDB({
    required this.bridge,
    required this.db,
  });

  Stream<void> connect({required String endpoint, dynamic hint}) =>
      bridge.connectMethodSurrealDb(
        that: this,
        endpoint: endpoint,
      );
}
